# Generated by Django 4.1 on 2022-09-23 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "food_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("food_name", models.CharField(max_length=30)),
                ("food_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("discount_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("food_desc", models.TextField()),
                ("food_image", models.ImageField(upload_to="food_images")),
            ],
        ),
        migrations.CreateModel(
            name="FoodCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_type", models.CharField(max_length=30)),
                ("food_category", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
                ("restaurant_type", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "restaurant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=60)),
                ("restaurant_location", models.CharField(max_length=100)),
                ("restaurant_features", models.CharField(max_length=120)),
                ("restaurnat_ratings", models.CharField(max_length=10)),
                ("restaurant_reviews", models.TextField()),
                ("restaurant_info", models.TextField()),
                ("restaurant_opening_closing_time", models.CharField(max_length=50)),
                (
                    "restaurant_image",
                    models.ImageField(
                        default="default.png", upload_to="restaurant_images"
                    ),
                ),
                (
                    "food_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landingpage.food",
                    ),
                ),
            ],
        ),
    ]
