# Generated by Django 4.1 on 2022-09-25 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "food_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("food_name", models.CharField(max_length=30)),
                ("food_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("discount_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("food_desc", models.TextField()),
                ("food_image", models.ImageField(upload_to="media/food_images")),
            ],
        ),
        migrations.CreateModel(
            name="FoodCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_category_image",
                    models.ImageField(
                        default="food.png", upload_to="media/food_categories_images"
                    ),
                ),
                ("food_category_name", models.CharField(max_length=50)),
                ("restaurant_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
                ("restaurant_type", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_features_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "restaurant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=60)),
                ("restaurant_location", models.CharField(max_length=100)),
                ("restaurnat_ratings", models.CharField(max_length=10)),
                ("restaurant_reviews", models.TextField()),
                ("restaurant_info", models.TextField()),
                ("restaurant_opening_closing_time", models.CharField(max_length=50)),
                ("total_tables", models.IntegerField()),
                ("available_tables", models.IntegerField()),
                ("booked_tables", models.IntegerField()),
                (
                    "restaurant_image",
                    models.ImageField(
                        default="default.png", upload_to="media/restaurant_images"
                    ),
                ),
                (
                    "restaurant_features",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landingpage.restaurantfeatures",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_quantity", models.IntegerField()),
                (
                    "food_total_price",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "foods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landingpage.food",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landingpage.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "menu_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("menu_price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "food_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landingpage.food",
                    ),
                ),
            ],
        ),
    ]
