# Generated by Django 4.1 on 2022-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_image", models.ImageField(upload_to="media/team_image")),
                ("team_name", models.CharField(max_length=25)),
                ("team_profession", models.CharField(max_length=25)),
            ],
        ),
    ]
