# Generated by Django 4.1 on 2022-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0002_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_type", models.CharField(max_length=20)),
                ("blog_title", models.CharField(max_length=50)),
                ("blog_posted_date", models.DateField()),
                ("blog_images", models.ImageField(upload_to="media/blog_images")),
                ("blog_desc", models.TextField()),
            ],
        ),
    ]
