# Generated by Django 4.1 on 2022-09-26 05:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0003_blog"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="blog_desc",),
        migrations.AddField(
            model_name="blog",
            name="blog_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
