# Generated by Django 4.1 on 2022-09-26 07:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0006_remove_blog_blog_desc_blog_blog_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="blog_description",),
        migrations.AddField(
            model_name="blog",
            name="blog_desc",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
